version: "3.7"

services:
  php-fpm:
    build:
      context: ci/local/php-fpm
      args:
        UID: "${uid}"
        GID: "${gid}"
    image: "mockery/php-fpm"
    restart: always
    volumes:
      - ./:/app
    networks:
      - mockery

  nginx:
    build:
      context: ci/local/nginx
    image: "mockery/nginx"
    restart: always
    ports:
      - ${NGINX_PORT}:80
    depends_on:
      - php-fpm
    links:
      - php-fpm
    volumes:
      - ./:/app
    networks:
      - mockery

  mongodb:
    image: mongo:4.2
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASS}
    ports:
      - ${MONGODB_PORT}:27017
    volumes:
      - mongodb_data:/data/db
    networks:
      - mockery

volumes:
  mongodb_data:

networks:
  mockery:
    driver: bridge